// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4jdi_hJOl7jo3hGwQPz57kIYetA2cL48',
    appId: '1:448727641317:web:fe74f4fa191472a1c4380c',
    messagingSenderId: '448727641317',
    projectId: 'musait-1c501',
    authDomain: 'musait-1c501.firebaseapp.com',
    storageBucket: 'musait-1c501.appspot.com',
    measurementId: 'G-65MKRK9TMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBG0fH1KzrrpCTqR_rZ-W5ra9TEGqXRXI',
    appId: '1:448727641317:android:9999f9f4c7e726fec4380c',
    messagingSenderId: '448727641317',
    projectId: 'musait-1c501',
    storageBucket: 'musait-1c501.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChOsa6AJjWzgIngwEPdpwQ6oB982MwENs',
    appId: '1:448727641317:ios:31cf0f0ff506d769c4380c',
    messagingSenderId: '448727641317',
    projectId: 'musait-1c501',
    storageBucket: 'musait-1c501.appspot.com',
    iosBundleId: 'com.example.musait',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChOsa6AJjWzgIngwEPdpwQ6oB982MwENs',
    appId: '1:448727641317:ios:b406c83b0cfc0290c4380c',
    messagingSenderId: '448727641317',
    projectId: 'musait-1c501',
    storageBucket: 'musait-1c501.appspot.com',
    iosBundleId: 'com.example.musait.RunnerTests',
  );
}
